#!/bin/bash

#----------------------------------------------------------------------
# Satin Startup Script
#----------------------------------------------------------------------

export CLASS_PATH=lib/'*'
export CLASS_PATH=$CLASS_PATH:etc

java -cp $CLASS_PATH alankstewart.satin.Satin
